### ISSUE TITLE
Not sure where else to open this

### ISSUE THREAD

**Issue by nicko170** [aplus-framework/app#1]
But why are you constantly unstarring and starring your repository?

This is "clogging" up mine, and I am sure everyone else's newsfeed with this crap, all day, every day. 

Are you just sitting there pressing unstar + star or have you written a bot to do this?

I am unfollowing all projects under this account now.

**Comment by HectorSpartan** [comment]
Hello @nicko170 !

I hope she don't bother you anymore.

Thanks. Have a great day.
