### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by c0destep** [aplus-framework/app#2]
Não encontrei na documentação algo relacionado a como fazer deploy em produção.

Como eu configuro meu ```.htaccess```?

**Comment by natanfelles** [comment]
Olá, @c0destep !

Ainda não foi escrito nada a respeito de como fazer deploy em produção.

Acredito que até dia 20 teremos isso pronto!

Por enquanto, sugestões de como configurar variados ambientes são muito bem vindas. :smiley:

**Comment by natanfelles** [comment]
Added .htaccess files in commit 96d13f402d76b8e7bacc4b176b50185b324c97f1.

Please test if it works in your environment.

**Comment by c0destep** [comment]
> Added .htaccess files in commit [96d13f4](https://github.com/aplus-framework/app/commit/96d13f402d76b8e7bacc4b176b50185b324c97f1).
> 
> Please test if it works in your environment.

Funcionou muito bem
