### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by valx76** [aplus-framework/app#3]
Hello,

Please stop having your fake accounts following me (messing stats/dashboard), I'm not interested..

I currently have:
@dinosoid
@phpfriend95
@aplus-developer
@CodePromoter
@alineai18
@carinalisboa
@athosss23

Thank you

**Comment by petabyt** [comment]
Same issue in 2023, had this and 3 other accounts follow me: https://github.com/carinalisboa?tab=stars (16 starred repositories all to aplus-framework)
